project_id = "hkstkuoixiogebynzatz"

[functions.analyze-code]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.fetch-github]
verify_jwt = false

[functions.generate-docs]
verify_jwt = false
